Fadiou/Models/Chambre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Fadiou.Models
{
    public class Chambre
    {
        [Key]
        public int idCh { get; set; }

        [MaxLength(2, ErrorMessage = "taille maximale 2"), 
            Required(ErrorMessage = "*")]
        [Display(Name = "Code")]
        public string codeCh { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"), 
            Required(ErrorMessage = "*")]
        [Display(Name = "Dénomination")]
        public string libelle { get; set; }      
        
    }
}

Fadiou/Controllers/ChambresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fadiou.Models;

namespace Fadiou.Controllers
{
    public class ChambresController : Controller
    {
        private bdFadiouContext db = new bdFadiouContext();

        // GET: Chambres
        public ActionResult Index()
        {
            return View(db.chambres.ToList());
        }

        // GET: Chambres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chambre chambre = db.chambres.Find(id);
            if (chambre == null)
            {
                return HttpNotFound();
            }
            return View(chambre);
        }

        // GET: Chambres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chambres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCh,codeCh,libelle")] Chambre chambre)
        {
            if (ModelState.IsValid)
            {
                db.chambres.Add(chambre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chambre);
        }

        // GET: Chambres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chambre chambre = db.chambres.Find(id);
            if (chambre == null)
            {
                return HttpNotFound();
            }
            return View(chambre);
        }

        // POST: Chambres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCh,codeCh,libelle")] Chambre chambre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chambre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chambre);
        }

        // GET: Chambres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chambre chambre = db.chambres.Find(id);
            if (chambre == null)
            {
                return HttpNotFound();
            }
            return View(chambre);
        }

        // POST: Chambres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chambre chambre = db.chambres.Find(id);
            db.chambres.Remove(chambre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fadiou/Views/Chambres/Create.cshtml
@model Fadiou.Models.Chambre

@{
    ViewBag.Title = "Nouvelle Chambre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nouvelle Chambre</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chambre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.codeCh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeCh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeCh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Valider" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Chambres/Delete.cshtml
@model Fadiou.Models.Chambre

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chambre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.codeCh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeCh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fadiou/Views/Chambres/Details.cshtml
@model Fadiou.Models.Chambre

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Chambre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.codeCh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeCh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idCh }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fadiou/Views/Chambres/Edit.cshtml
@model Fadiou.Models.Chambre

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chambre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idCh)

        <div class="form-group">
            @Html.LabelFor(model => model.codeCh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeCh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeCh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Chambres/Index.cshtml
@model IEnumerable<Fadiou.Models.Chambre>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des chambres</h2>

<p>
    <a class="btn btn-app" href="@Url.Action("Create", "Chambres")" title="Nouveau">
        <i class="fa fa-save"></i> Nouveau
    </a>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codeCh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.codeCh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.libelle)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Chambres", new { id=item.idCh })" title="Modifier">
                <i class="fa fa-edit"></i>
            </a>|
            <a href="@Url.Action("Delete", "Chambres", new { id=item.idCh })" title="Supprimer">
                <i class="fa fa-remove"></i>
            </a>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.idCh }) |
        @Html.ActionLink("Details", "Details", new { id=item.idCh }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.idCh })*@
        </td>
    </tr>
}

</table>