Fadiou/Models/Lit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Fadiou.Models
{
    public class Lit
    {
        [Key]
        public int idLit { get; set; }

        [MaxLength(2, ErrorMessage = "taille maximale 2"), 
            Required(ErrorMessage = "*")]
        [Display(Name = "Code Lit")]
        public string codeLit { get; set; }

        public int  idChambre { get; set; }
        [ForeignKey("idChambre")]
        public virtual Chambre Chambre { get; set; }
    }
}

Fadiou/Controllers/LitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fadiou.Models;

namespace Fadiou.Controllers
{
    public class LitsController : Controller
    {
        private bdFadiouContext db = new bdFadiouContext();

        // GET: Lits
        public ActionResult Index()
        {
            
            var lits = db.lits.Include(l => l.Chambre);
            return View(lits.ToList());
        }

        // GET: Lits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lit lit = db.lits.Find(id);
            if (lit == null)
            {
                return HttpNotFound();
            }
            return View(lit);
        }

        // GET: Lits/Create
        public ActionResult Create()
        {
            ViewBag.Chambre = db.chambres.ToList();
            //ViewBag.idChambre = new SelectList(db.chambres, "idCh", "codeCh");
            return View();
        }

        // POST: Lits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idLit,codeLit,idChambre")] Lit lit)
        {
            if (ModelState.IsValid)
            {
                db.lits.Add(lit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idChambre = new SelectList(db.chambres, "idCh", "codeCh", lit.idChambre);
            return View(lit);
        }

        // GET: Lits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lit lit = db.lits.Find(id);
            if (lit == null)
            {
                return HttpNotFound();
            }
            ViewBag.idChambre = new SelectList(db.chambres, "idCh", "codeCh", lit.idChambre);
            return View(lit);
        }

        // POST: Lits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idLit,codeLit,idChambre")] Lit lit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idChambre = new SelectList(db.chambres, "idCh", "codeCh", lit.idChambre);
            return View(lit);
        }

        // GET: Lits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lit lit = db.lits.Find(id);
            if (lit == null)
            {
                return HttpNotFound();
            }
            return View(lit);
        }

        // POST: Lits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lit lit = db.lits.Find(id);
            db.lits.Remove(lit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fadiou/Views/Lits/Create.cshtml
@model Fadiou.Models.Lit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.codeLit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeLit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeLit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idChambre, "idChambre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("idChambre", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownList("idChambre", new SelectList(ViewBag.Chambre, "idCh", "Libelle"), "Selectionnez...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idChambre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Lits/Delete.cshtml
@model Fadiou.Models.Lit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chambre.codeCh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chambre.codeCh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codeLit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeLit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fadiou/Views/Lits/Details.cshtml
@model Fadiou.Models.Lit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Lit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chambre.codeCh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chambre.codeCh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codeLit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeLit)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idLit }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fadiou/Views/Lits/Edit.cshtml
@model Fadiou.Models.Lit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idLit)

        <div class="form-group">
            @Html.LabelFor(model => model.codeLit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeLit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeLit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idChambre, "idChambre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idChambre", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idChambre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Lits/Index.cshtml
@model IEnumerable<Fadiou.Models.Lit>

@{
    ViewBag.Title = "Liste des lits";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des lits</h2>

<p>
    <a class="btn btn-app" href="@Url.Action("Create", "Lits")" title="Nouveau">
        <i class="fa fa-save"></i> Nouveau
    </a>
    @*@Html.ActionLink("Nouveau", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Chambre.libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.codeLit)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Chambre.libelle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.codeLit)
        </td>
        <td>
            <a class="btn btn-app" href="@Url.Action("Edit", "Lits", new { id=item.idLit })" title="Modifier">
                <i class="fa fa-edit"></i>
            </a>|
            <a class="btn btn-app" href="@Url.Action("Delete", "Lits", new { id=item.idLit })" title="Supprimer">
                <i class="fa fa-remove"></i>
            </a>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.idLit }) |
        @Html.ActionLink("Details", "Details", new { id=item.idLit }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.idLit })*@
        </td>
    </tr>
}

</table>