Fadiou/Models/Infirmier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Fadiou.Models
{
    public class Infirmier
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int idInf { get; set; }
        [ForeignKey("idInf")]
        public virtual Personne personne { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"), 
            Required(ErrorMessage = "*")]
        [Display(Name = "Specialite")]
        public string specialteInf { get; set; }
    }
}

Fadiou/Models/InfirmierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Fadiou.Models
{
    public class InfirmierViewModel
    {
        [Key]
        public int idPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Nom")]
        public string nomPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Prenom")]
        public string prenomPers { get; set; }

        [MaxLength(150, ErrorMessage = "taille maximale 150"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Addresse")]
        public string adressePers { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "DateNaiss")]
        public DateTime dateNaissancePers { get; set; }

        [MaxLength(10, ErrorMessage = "taille maximale 10"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Sexe")]
        public string sexePers { get; set; }

        [MaxLength(30, ErrorMessage = "taille maximale 30"),
            Required(ErrorMessage = "*")]
        [Display(Name = "CNI")]
        public string cniPers { get; set; }

        [MaxLength(40, ErrorMessage = "taille maximale 40"),
            Required(ErrorMessage = "*")]
        [Display(Name = "SituationMat")]
        public string situationMatPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Email"), DataType(DataType.EmailAddress)]
        public string emailPers { get; set; }

        [MaxLength(15, ErrorMessage = "taille maximale 15"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Telephone"), DataType(DataType.PhoneNumber)]
        public string telPers { get; set; }
        [MaxLength(80, ErrorMessage = "taille maximale 80"),
          Required(ErrorMessage = "*")]
        [Display(Name = "Specialite")]
        public string specialteInf { get; set; }
    }
}

Fadiou/Controllers/InfirmierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fadiou.Models;
using PagedList;

namespace Fadiou.Controllers
{
    public class InfirmierController : Controller
    {
        private bdFadiouContext db = new bdFadiouContext();

        // GET: Infirmier
        public ActionResult Index(int? page)
        {
            page = page.HasValue ? page : 1;
            int sizePage = 2;
            //int pageNumber = (page ?? 1);
            var lesinfirmiers = getListInfirmiers().ToList();
            return View(lesinfirmiers.ToPagedList((int)page, sizePage));
           // return View(db.personnes.ToList());
        }

        // GET: Infirmier/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    InfirmierViewModel infirmierViewModel = db.InfirmierViewModels.Find(id);
        //    if (infirmierViewModel == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(infirmierViewModel);
        //}

        // GET: Infirmier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Infirmier/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPers,nomPers,prenomPers,adressePers,dateNaissancePers,sexePers,cniPers,situationMatPers,emailPers,telPers,specialteInf")] InfirmierViewModel infirmierViewModel)
        {
            if (ModelState.IsValid)
            {
                Personne p = new Personne();
                p.adressePers = infirmierViewModel.adressePers;
                p.cniPers = infirmierViewModel.cniPers;
                p.dateNaissancePers = infirmierViewModel.dateNaissancePers;
                p.emailPers = infirmierViewModel.emailPers;
                p.nomPers = infirmierViewModel.nomPers;
                p.prenomPers = infirmierViewModel.prenomPers;
                p.sexePers = infirmierViewModel.sexePers;
                p.situationMatPers = infirmierViewModel.situationMatPers;
                p.telPers = infirmierViewModel.telPers;
                db.personnes.Add(p);
                db.SaveChanges();
                Infirmier inf = new Infirmier();
                inf.idInf = p.idPers;
                inf.specialteInf = infirmierViewModel.specialteInf;
                db.infirmiers.Add(inf);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(infirmierViewModel);
        }

        // GET: Infirmier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            InfirmierViewModel infirmierViewModel = getListInfirmiers().Where(a => a.idPers == id).FirstOrDefault();
            if (infirmierViewModel == null)
            {
                return HttpNotFound();
            }
            return View(infirmierViewModel);
        }

        // POST: Infirmier/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPers,nomPers,prenomPers,adressePers,dateNaissancePers,sexePers,cniPers,situationMatPers,emailPers,telPers,specialteInf")] InfirmierViewModel infirmierViewModel)
        {
            if (ModelState.IsValid)
            {
                Personne p = db.personnes.Find(infirmierViewModel.idPers);
                p.adressePers = infirmierViewModel.adressePers;
                p.cniPers = infirmierViewModel.cniPers;
                p.dateNaissancePers = infirmierViewModel.dateNaissancePers;
                p.emailPers = infirmierViewModel.emailPers;
                p.nomPers = infirmierViewModel.nomPers;
                p.prenomPers = infirmierViewModel.prenomPers;
                p.sexePers = infirmierViewModel.sexePers;
                p.situationMatPers = infirmierViewModel.situationMatPers;
                p.telPers = infirmierViewModel.telPers;
                db.SaveChanges();
                Infirmier inf = db.infirmiers.Find(infirmierViewModel.idPers);
                inf.specialteInf = infirmierViewModel.specialteInf;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(infirmierViewModel);
        }

        // GET: Infirmier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InfirmierViewModel infirmierViewModel = getListInfirmiers().Where(a => a.idPers == id).FirstOrDefault();
            if (infirmierViewModel == null)
            {
                return HttpNotFound();
            }
            return View(infirmierViewModel);
        }

        // POST: Infirmier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Infirmier inf = db.infirmiers.Find(id);
            db.infirmiers.Remove(inf);
            db.SaveChanges();
            Personne p = db.personnes.Find(id);
            db.personnes.Remove(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult listeDesPersonnes()
        {
            return View(db.personnes.ToList());
        }
        public ActionResult listdesMedecins()
        {
            return View(db.infirmiers.Include(a => a.personne).ToList());
        }

        public List<InfirmierViewModel> getListInfirmiers()
        {
            var listPersonne = db.infirmiers.ToList();
            List<InfirmierViewModel> lesInfirmiers = new List<InfirmierViewModel>();
            foreach (var x in listPersonne)
            {
                InfirmierViewModel inf = new InfirmierViewModel();
                var i = db.personnes.Find(x.idInf);

                inf.idPers = i.idPers;
                inf.nomPers = i.nomPers;
                inf.adressePers = i.adressePers;
                inf.cniPers = i.cniPers;
                inf.dateNaissancePers = i.dateNaissancePers;
                inf.emailPers = i.emailPers;
                inf.prenomPers = i.prenomPers;
                inf.sexePers = i.sexePers;
                inf.situationMatPers = i.situationMatPers;
                inf.specialteInf = x.specialteInf;
                inf.telPers = i.telPers;
                lesInfirmiers.Add(inf);
            }
            return lesInfirmiers;
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fadiou/Views/Infirmier/Create.cshtml
@model Fadiou.Models.InfirmierViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InfirmierViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adressePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adressePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adressePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateNaissancePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateNaissancePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateNaissancePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sexePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sexePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cniPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cniPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cniPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.situationMatPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.situationMatPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.situationMatPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.specialteInf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.specialteInf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.specialteInf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Infirmier/Delete.cshtml
@model Fadiou.Models.InfirmierViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InfirmierViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adressePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adressePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateNaissancePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateNaissancePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cniPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cniPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.situationMatPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.situationMatPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialteInf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialteInf)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fadiou/Views/Infirmier/Details.cshtml
@model Fadiou.Models.InfirmierViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>InfirmierViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adressePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adressePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateNaissancePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateNaissancePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cniPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cniPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.situationMatPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.situationMatPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialteInf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialteInf)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idPers }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fadiou/Views/Infirmier/Edit.cshtml
@model Fadiou.Models.InfirmierViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InfirmierViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idPers)

        <div class="form-group">
            @Html.LabelFor(model => model.nomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adressePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adressePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adressePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateNaissancePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateNaissancePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateNaissancePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sexePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sexePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cniPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cniPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cniPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.situationMatPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.situationMatPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.situationMatPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.specialteInf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.specialteInf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.specialteInf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Infirmier/Index.cshtml
@model PagedList.IPagedList<Fadiou.Models.InfirmierViewModel>
@using PagedList.Mvc;


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    <a href="@Url.Action("Create", "Infirmier")" title="Nouveau" class="btn btn-app">
        <i class="fa fa-save"></i>Nouveau
    </a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().nomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().prenomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().sexePers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().emailPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().telPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().specialteInf)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nomPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prenomPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sexePers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.emailPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.specialteInf)
            </td>
            <td>
                <a class="btn btn-app" href="@Url.Action("Edit", "Infirmier", new { id=item.idPers })" title="Modifier">
                    <i class="fa fa-edit"></i>
                </a>|
                <a class="btn btn-app" href="@Url.Action("Delete", "Infirmier", new { id=item.idPers })" title="Supprimer">
                    <i class="fa fa-remove"></i>
                </a>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.idPers }) |
                    @Html.ActionLink("Details", "Details", new { id = item.idPers }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.idPers })*@
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }))

Fadiou/Views/Infirmier/listdesInfirmiers.cshtml
@model IEnumerable<Fadiou.Models.Infirmier>

@{
    ViewBag.Title = "listdesInfirmiers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>listdesInfirmiers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.personne.nomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personne.prenomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personne.adressePers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.specialteInf)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.personne.nomPers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.personne.prenomPers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.personne.adressePers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.specialteInf)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.idInf }) |
            @Html.ActionLink("Details", "Details", new { id = item.idInf }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.idInf })
        </td>
    </tr>
}

</table>