Fadiou/Models/MedcinViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Fadiou.Models
{
    public class MedcinViewModel
    {
        [Key]
        public int idPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Nom")]
        public string nomPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Prénom")]
        public string prenomPers { get; set; }

        [MaxLength(150, ErrorMessage = "taille maximale 150"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Adresse")]
        public string adressePers { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Date de Naissance")]
        public DateTime dateNaissancePers { get; set; }

        [MaxLength(10, ErrorMessage = "taille maximale 10"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Sexe")]
        public string sexePers { get; set; }

        [MaxLength(30, ErrorMessage = "taille maximale 30"),
            Required(ErrorMessage = "*")]
        [Display(Name = "CNI")]
        public string cniPers { get; set; }

        [MaxLength(40, ErrorMessage = "taille maximale 40"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Situation Matrimoniale")]
        public string situationMatPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Email"), DataType(DataType.EmailAddress)]
        public string emailPers { get; set; }

        [MaxLength(15, ErrorMessage = "taille maximale 15"),
            Required(ErrorMessage = "*")]
        [Display(Name = "Téléphone"), DataType(DataType.PhoneNumber)]
        public string telPers { get; set; }

        [MaxLength(80, ErrorMessage = "taille maximale 80"),
          Required(ErrorMessage = "*")]
        [Display(Name = "Spécialite")]
        public string specialteMed { get; set; }
    }
}

Fadiou/Controllers/MedcinController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fadiou.Models;
using PagedList;

namespace Fadiou.Controllers
{
    public class MedcinController : Controller
    {
        private bdFadiouContext db = new bdFadiouContext();

        // GET: Medcin
        public ActionResult Index(int? page, string Nom, string Prenom)
        {
            ViewBag.Nom = !string.IsNullOrEmpty(Nom) ? Nom : string.Empty;
            ViewBag.Prenom = !string.IsNullOrEmpty(Prenom) ? Prenom : string.Empty;

            page = page.HasValue ? page : 1;
            int sizePage = 10;
            var lesMedecins = getListMedecin().ToList();
            if (!string.IsNullOrEmpty(Nom))
            {
                lesMedecins = lesMedecins.Where(a => a.nomPers.ToUpper().Contains(Nom.ToUpper())).ToList();
            }
            if (!string.IsNullOrEmpty(Prenom))
            {
                lesMedecins = lesMedecins.Where(a => a.prenomPers.ToUpper().Contains(Prenom.ToUpper())).ToList();
            }
            return View(lesMedecins.ToPagedList((int)page, sizePage));
            // return View(lesMedecins.ToPagedList(sizePage, pageNumber));
        }

        // GET: Medcin/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    MedcinViewModel medcinViewModel = db.MedcinViewModels.Find(id);
        //    if (medcinViewModel == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(medcinViewModel);
        //}

        // GET: Medcin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medcin/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPers,nomPers,prenomPers,adressePers,dateNaissancePers,sexePers,cniPers,situationMatPers,emailPers,telPers,specialteMed")] MedcinViewModel medcinViewModel)
        {
            if (ModelState.IsValid)
            {
                //db.MedcinViewModels.Add(medcinViewModel);
                Personne p = new Personne();
                p.adressePers = medcinViewModel.adressePers;
                p.cniPers = medcinViewModel.cniPers;
                p.dateNaissancePers = medcinViewModel.dateNaissancePers;
                p.emailPers = medcinViewModel.emailPers;
                p.nomPers = medcinViewModel.nomPers;
                p.prenomPers = medcinViewModel.prenomPers;
                p.sexePers = medcinViewModel.sexePers;
                p.situationMatPers = medcinViewModel.situationMatPers;
                p.telPers = medcinViewModel.telPers;
                db.personnes.Add(p);
                db.SaveChanges();
                Medecin m = new Medecin();
                m.idMed = p.idPers;
                m.specialteMed = medcinViewModel.specialteMed;
                //m.personne = p;
                db.medecins.Add(m);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medcinViewModel);
        }

        // GET: Medcin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedcinViewModel medcinViewModel = getListMedecin().Where(a => a.idPers == id).FirstOrDefault();
            if (medcinViewModel == null)
            {
                return HttpNotFound();
            }
            return View(medcinViewModel);
        }

        // POST: Medcin/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPers,nomPers,prenomPers,adressePers,dateNaissancePers,sexePers,cniPers,situationMatPers,emailPers,telPers,specialteMed")] MedcinViewModel medcinViewModel)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(medcinViewModel).State = EntityState.Modified;
                //db.SaveChanges();
                Personne p = db.personnes.Find(medcinViewModel.idPers);
                p.adressePers = medcinViewModel.adressePers;
                p.cniPers = medcinViewModel.cniPers;
                p.dateNaissancePers = medcinViewModel.dateNaissancePers;
                p.emailPers = medcinViewModel.emailPers;
                p.nomPers = medcinViewModel.nomPers;
                p.prenomPers = medcinViewModel.prenomPers;
                p.sexePers = medcinViewModel.sexePers;
                p.situationMatPers = medcinViewModel.situationMatPers;
                p.telPers = medcinViewModel.telPers;
                // db.personnes.Add(p); //pas besoin de faire un add 
                db.SaveChanges();
                Medecin m = db.medecins.Find(medcinViewModel.idPers);
                m.specialteMed = medcinViewModel.specialteMed;
                //m.personne = p;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medcinViewModel);
        }

        // GET: Medcin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedcinViewModel medcinViewModel = getListMedecin().Where(a => a.idPers == id).FirstOrDefault();
            if (medcinViewModel == null)
            {
                return HttpNotFound();
            }
            return View(medcinViewModel);
        }

        // POST: Medcin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //MedcinViewModel medcinViewModel = db.MedcinViewModels.Find(id);
            //db.MedcinViewModels.Remove(medcinViewModel);
            //db.SaveChanges();
            // Delete Medecin First
            Medecin m = db.medecins.Find(id);
            db.medecins.Remove(m);
            db.SaveChanges();
            Personne p = db.personnes.Find(id);
            db.personnes.Remove(p);
            db.SaveChanges();
           
            return RedirectToAction("Index");
        }

        public ActionResult listeDesPersonnes()
        {
            return View(db.personnes.ToList());
        }

        public ActionResult listdesMedecins()
        {
            return View(db.medecins.Include(a => a.personne).ToList());
        }

        public List<MedcinViewModel> getListMedecin()
        {
            var listPersonne = db.medecins.ToList();
            List<MedcinViewModel> lesMedecins = new List<MedcinViewModel>();
            foreach(var x in listPersonne)
            {
                MedcinViewModel m = new MedcinViewModel();
                var i = db.personnes.Find(x.idMed);
                m.idPers = i.idPers;
                m.nomPers = i.nomPers;
                m.adressePers = i.adressePers;
                m.cniPers = i.cniPers;
                m.dateNaissancePers = i.dateNaissancePers;
                m.emailPers = i.emailPers;
                m.prenomPers = i.prenomPers;
                m.sexePers = i.sexePers;
                m.situationMatPers = i.situationMatPers;
                m.specialteMed = x.specialteMed;
                m.telPers = i.telPers;
                lesMedecins.Add(m);
            }
            return lesMedecins;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fadiou/Views/Medcin/Create.cshtml
@model Fadiou.Models.MedcinViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MedcinViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adressePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adressePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adressePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateNaissancePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateNaissancePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateNaissancePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sexePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sexePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cniPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cniPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cniPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.situationMatPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.situationMatPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.situationMatPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.specialteMed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.specialteMed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.specialteMed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Medcin/Delete.cshtml
@model Fadiou.Models.MedcinViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MedcinViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adressePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adressePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateNaissancePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateNaissancePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cniPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cniPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.situationMatPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.situationMatPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialteMed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialteMed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fadiou/Views/Medcin/Details.cshtml
@model Fadiou.Models.MedcinViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MedcinViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenomPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenomPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adressePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adressePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateNaissancePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateNaissancePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexePers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexePers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cniPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cniPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.situationMatPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.situationMatPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telPers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telPers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialteMed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialteMed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idPers }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fadiou/Views/Medcin/Edit.cshtml
@model Fadiou.Models.MedcinViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MedcinViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idPers)

        <div class="form-group">
            @Html.LabelFor(model => model.nomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenomPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenomPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenomPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adressePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adressePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adressePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateNaissancePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateNaissancePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateNaissancePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexePers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sexePers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sexePers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cniPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cniPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cniPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.situationMatPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.situationMatPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.situationMatPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telPers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telPers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telPers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.specialteMed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.specialteMed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.specialteMed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fadiou/Views/Medcin/Index.cshtml
@*@model IEnumerable<Fadiou.Models.MedcinViewModel>*@
@model PagedList.IPagedList<Fadiou.Models.MedcinViewModel>
@using PagedList.Mvc;


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    <a href="@Url.Action("Create", "Medcin")" title="Nouveau" class="btn btn-app">
        <i class="fa fa-save"></i>Nouveau
    </a>
</p>
<div class="row">
    <div class="col-xs-12 col-md-12">
        <div class="widget">
            <div class="widget-body">
                @using (Html.BeginForm("Index", "Medcin", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <b>Nom</b> @Html.TextBox("Nom", ViewBag.Nom as string, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <b>Prénom</b> @Html.TextBox("Prenom", ViewBag.Prenom as string, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <input type="submit" value="Rechercher" class="btn btn-primary" />
                    </div>
                }

            </div>
        </div>
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().nomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().prenomPers)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.First().sexePers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().emailPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().telPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().specialteMed)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nomPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prenomPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sexePers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.emailPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telPers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.specialteMed)
            </td>
            <td>
                <a class="btn btn-app" href="@Url.Action("Edit", "Medcin", new { id=item.idPers })" title="Modifier">
                    <i class="fa fa-edit"></i>
                </a>|
                <a class="btn btn-app" href="@Url.Action("Delete", "Medcin", new { id=item.idPers })" title="Supprimer">
                    <i class="fa fa-remove"></i>
                </a>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.idPers }) |
                    @Html.ActionLink("Details", "Details", new { id=item.idPers }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.idPers })*@
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, Page =>Url.Action("Index", new { Page, Nom=ViewBag.Nom, Prenom=ViewBag.Prenom }))

Fadiou/Views/Medcin/listdesMedecins.cshtml
@model IEnumerable<Fadiou.Models.Medecin>

@{
    ViewBag.Title = "listdesMedecins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>listdesMedecins</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.personne.nomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personne.prenomPers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personne.adressePers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.specialteMed)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.personne.nomPers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.personne.prenomPers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.personne.adressePers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.specialteMed)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.idMed }) |
            @Html.ActionLink("Details", "Details", new { id = item.idMed }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.idMed })
        </td>
    </tr>
}

</table>